### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by jim-rosales** [Catallactic369/Von-toshi-metz#4]
Your stylesheet doesn't follow formatting conventions when it comes to CSS rules. Take a look at this style guide which has excellent guidelines to improve the readability of your CSS file. You can also review this CSS solution for the project to get a sense of the different readability levels of your stylesheet and the provided one. 

For this rule you'd want to format it in the following way: 
```CSS
h1 {
  font-family: Helvetivca;
  font-size: 139px;
  color: khaki;
  font-weight: bold;
  text-align: center;
  text-shadow: 2px 2px 5px teal;
  background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
}
```

https://github.com/Catallactic369/Von-toshi-metz/blob/bc56ad6a54d8aefc7637fdca4cdb4bd5fb70fac1/style.css#L1-L5
